version: "3"

services:
    mc:
        container_name: minecraftServ1.19
        image: itzg/minecraft-server
        ports:
            - 25565:25565
        environment:
            EULA: "TRUE"
            TYPE: "FORGE"
            VERSION: 1.19.3
            # MODS_FILE: /extras/mods.txt
            # REMOVE_OLD_MODS: "true"
        tty: true
        stdin_open: true
        restart: unless-stopped
        volumes:
            - ./minecraft-data:/data
            - ./mods.txt:/extras/mods.txt:ro
volumes:
    data:
